Repository techeer-sv/SpotlightSeoul, pull requests merged in 2023-10, with the labels that each got.

#25 BE/#24 Festival 전체 조회 api 구현
  backend/src/main/java/com/example/backend/domain/festival/controller/FestivalController.java
  backend/src/main/java/com/example/backend/domain/festival/dto/response/FestivalPageResponse.java
  backend/src/main/java/com/example/backend/domain/festival/dto/response/FestivalResponse.java
  backend/src/main/java/com/example/backend/domain/festival/mapper/FestivalMapper.java
  backend/src/main/java/com/example/backend/domain/festival/repository/FestivalRepository.java
  backend/src/main/java/com/example/backend/domain/festival/service/FestivalService.java
Labels: 기능구현

#20 BE/#9 User에 대한 기본 CRUD 구현
  backend/src/main/java/com/example/backend/domain/user/controller/UserController.java
  backend/src/main/java/com/example/backend/domain/user/dto/request/UserCreateRequest.java
  backend/src/main/java/com/example/backend/domain/user/dto/request/UserUpdateRequest.java
  backend/src/main/java/com/example/backend/domain/user/dto/response/UserResponse.java
  backend/src/main/java/com/example/backend/domain/user/entity/User.java
  backend/src/main/java/com/example/backend/domain/user/mapper/UserMapper.java
  backend/src/main/java/com/example/backend/domain/user/repository/UserRepository.java
  backend/src/main/java/com/example/backend/domain/user/service/UserService.java
Labels: 기능구현

#27 Fe/#11 메인페이지 퍼블리싱 및 반응형
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/assets/images/jpg/exampleThum.jpeg
  frontend/src/assets/lottie.tsx
  frontend/src/assets/lottie/search.json
  frontend/src/components/Banner.tsx
  frontend/src/components/Filter.tsx
  frontend/src/components/Paging.css
  frontend/src/components/Paging.tsx
  frontend/src/components/PostCard.tsx
  frontend/src/pages/MainPage.tsx
  frontend/yarn.lock
  요소/exampleThum.jpeg
Labels: 퍼블리싱

#32 Fe/#30 MapInformation 네이버지도 API 구현
  frontend/index.html
  frontend/package.json
  frontend/src/components/MapInformation.tsx
  frontend/yarn.lock
Labels: 기능구현

#36 Fe/#33 프론트엔드 Dockerfile 세팅
  frontend/.dockerignore
  frontend/Dockerfile
  frontend/vite.config.ts
Labels: 기타/세팅

#37 Fe/#34 메인페이지 design 세부수정
  frontend/src/components/Banner.tsx
  frontend/src/components/Filter.tsx
Labels: 디자인

#42 Be/#39 유무료 추가 및 상세페이지 유뮤료 추가
  backend/src/main/java/com/example/backend/api/data/vo/FestivalRow.java
  backend/src/main/java/com/example/backend/domain/festival/controller/FestivalController.java
  backend/src/main/java/com/example/backend/domain/festival/dto/response/FestivalDetailResponse.java
  backend/src/main/java/com/example/backend/domain/festival/entity/Festival.java
  backend/src/main/java/com/example/backend/domain/festival/mapper/FestivalMapper.java
  backend/src/main/java/com/example/backend/domain/festival/service/FestivalService.java
Labels: 기능구현

#45 Fe/#44 상세페이지 API 연동
  frontend/index.html
  frontend/src/components/FestivalInformation.tsx
  frontend/src/components/MapInformation.tsx
  frontend/src/main.tsx
  frontend/src/pages/DetailPage.tsx
  frontend/tsconfig.json
  frontend/yarn.lock
Labels: 기능구현

#49 Fe/#47 상세페이지 요금 유/무료로 변경
  frontend/src/components/FestivalInformation.tsx
  frontend/src/pages/DetailPage.tsx
Labels: 기능구현

#48 Be/#46 대분류 소분류 추가
  backend/src/main/java/com/example/backend/domain/festival/entity/Festival.java
  backend/src/main/java/com/example/backend/domain/festival/mapper/FestivalMapper.java
  backend/src/main/java/com/example/backend/domain/festival/utils/EventCategoryUtil.java
  backend/src/main/java/com/example/backend/global/config/web/CorsConfig.java
Labels: 기능구현

#53 BE/#52 상세페이지 분류-> 대분류, 소분류로 분리
  backend/src/main/java/com/example/backend/domain/festival/dto/response/FestivalDetailResponse.java
  backend/src/main/java/com/example/backend/domain/festival/mapper/FestivalMapper.java
Labels: 리팩토링

#55 Fe/#54 상세페이지 response data 최신화
  frontend/index.html
  frontend/src/components/FestivalInformation.tsx
  frontend/src/pages/DetailPage.tsx
Labels: 기능구현

#58 Be/#57 요구사항에 따른 데이터 변경
  backend/src/main/java/com/example/backend/domain/festival/dto/response/FestivalPageResponse.java
  backend/src/main/java/com/example/backend/domain/festival/dto/response/FestivalResponse.java
  backend/src/main/java/com/example/backend/domain/festival/mapper/FestivalMapper.java
  backend/src/main/java/com/example/backend/domain/festival/service/FestivalService.java
Labels: 기능구현, 리팩토링

#56 Be/#50 검색 api 띄어쓰기 구현 및 선택 검색 api 구현
  backend/build.gradle
  backend/src/main/java/com/example/backend/domain/festival/controller/FestivalController.java
  backend/src/main/java/com/example/backend/domain/festival/dto/response/FestivalFilterResponse.java
  backend/src/main/java/com/example/backend/domain/festival/dto/response/FestivalFilterSearchResponse.java
  backend/src/main/java/com/example/backend/domain/festival/mapper/FestivalMapper.java
  backend/src/main/java/com/example/backend/domain/festival/repository/FestivalRepository.java
  backend/src/main/java/com/example/backend/domain/festival/repository/FestivalRepositoryCustom.java
  backend/src/main/java/com/example/backend/domain/festival/repository/FestivalRepositoryImpl.java
  backend/src/main/java/com/example/backend/domain/festival/service/FestivalService.java
Labels: 기능구현

#60 Fe/#31 메인페이지 PostCard 기능구현 및 API연동
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/components/PostCard.tsx
  frontend/src/pages/MainPage.tsx
Labels: 기능구현

#65 Be/#61 검색 api 데이터 변경 및 전체페이지 조회 추가
  backend/src/main/java/com/example/backend/api/data/vo/FestivalRow.java
  backend/src/main/java/com/example/backend/domain/festival/controller/FestivalController.java
  backend/src/main/java/com/example/backend/domain/festival/dto/request/FestivalSearchRequest.java
  backend/src/main/java/com/example/backend/domain/festival/dto/response/FestivalFilterPageResponse.java
  backend/src/main/java/com/example/backend/domain/festival/dto/response/FestivalFilterResponse.java
  backend/src/main/java/com/example/backend/domain/festival/dto/response/FestivalFilterSearchResponse.java
  backend/src/main/java/com/example/backend/domain/festival/dto/response/FestivalSearchPageResponse.java
  backend/src/main/java/com/example/backend/domain/festival/dto/response/FestivalSearchResponse.java
  backend/src/main/java/com/example/backend/domain/festival/entity/Festival.java
  backend/src/main/java/com/example/backend/domain/festival/mapper/FestivalMapper.java
  backend/src/main/java/com/example/backend/domain/festival/repository/FestivalRepository.java
  backend/src/main/java/com/example/backend/domain/festival/repository/FestivalRepositoryCustom.java
  backend/src/main/java/com/example/backend/domain/festival/repository/FestivalRepositoryImpl.java
  backend/src/main/java/com/example/backend/domain/festival/service/FestivalService.java
  backend/src/main/java/com/example/backend/global/utils/TimeFormatter.java
Labels: 기능구현, 리팩토링

#66 Fe/#64 메인페이지 기능구현 수정
  frontend/src/components/Filter.tsx
  frontend/src/components/Paging.tsx
  frontend/src/components/PostCard.tsx
  frontend/src/pages/MainPage.tsx
Labels: 기능구현

#69 Fe/#63 상세페이지 id값 연결
  frontend/src/pages/DetailPage.tsx
Labels: 기능구현

#71 Fe/#62 네비게이션 바 검색 기능 구현
  frontend/src/RecoilState.ts
  frontend/src/components/NavBar.tsx
  frontend/src/components/PostCard.tsx
  frontend/src/pages/MainPage.tsx
Labels: 기능구현, 디자인

#72 Fe/#68 메인페이지 기능 구현 관련
  frontend/src/components/Filter.tsx
  frontend/src/components/PostCard.tsx
  frontend/src/pages/MainPage.tsx
Labels: 기능구현

#75 FE/#74 검색 시 카테고리, 날짜 데이터 안보이는 것 수정
  frontend/src/RecoilState.ts
  frontend/src/components/NavBar.tsx
  frontend/src/pages/MainPage.tsx
Labels: 오류수정
