Repository techeer-sv/SpotlightSeoul, pull requests merged in 2023-09, with the labels that each got.

#3 Be/#1
  .gitignore
  backend/.env.template
  backend/.gitignore
  backend/Dockerfile
  backend/build.gradle
  backend/docker-compose.yml
  backend/gradle/wrapper/gradle-wrapper.jar
  backend/gradle/wrapper/gradle-wrapper.properties
  backend/gradlew
  backend/gradlew.bat
  backend/settings.gradle
  backend/src/main/java/com/example/backend/BackendApplication.java
  backend/src/main/java/com/example/backend/global/advice/ErrorAdvice.java
  backend/src/main/java/com/example/backend/global/advice/ErrorResponse.java
  backend/src/main/java/com/example/backend/global/audit/AuditListener.java
  backend/src/main/java/com/example/backend/global/audit/Auditable.java
  backend/src/main/java/com/example/backend/global/audit/BaseTime.java
  backend/src/main/java/com/example/backend/global/config/audit/JpaAuditingConfig.java
  backend/src/main/java/com/example/backend/global/config/mapper/ObjectMapperConfig.java
  backend/src/main/java/com/example/backend/global/dto/IdResponse.java
  backend/src/main/java/com/example/backend/global/exception/EntityNotFoundException.java
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application-local.yml
  backend/src/test/java/com/example/backend/BackendApplicationTests.java
Labels: 기타/세팅

#5 Fe/#1 프론트엔드 초기세팅
  frontend/.eslintrc.cjs
  frontend/.gitignore
  frontend/.prettierrc
  frontend/README.md
  frontend/dist/output.css
  frontend/index.html
  frontend/package.json
  frontend/postcss.config.js
  frontend/public/vite.svg
  frontend/src/App.css
  frontend/src/App.tsx
  frontend/src/assets/react.svg
  frontend/src/index.css
  frontend/src/main.tsx
  frontend/src/vite-env.d.ts
  frontend/tailwind.config.js
  frontend/tsconfig.json
  frontend/tsconfig.node.json
  frontend/vite.config.ts
  frontend/yarn.lock
Labels: 기타/세팅

#7 Fe/#6 Prettier 적용 안되는 오류 수정
  frontend/.eslintrc.cjs
Labels: 오류수정

#10 FE/#8 navigation bar 퍼블리싱
  frontend/src/App.css
  frontend/src/App.tsx
  frontend/src/assets/fonts/LexendDeca-VariableFont_wght.ttf
  frontend/src/assets/images/svg/magnifier.svg
  frontend/src/assets/react.svg
  frontend/src/components/NavBar.tsx
  frontend/src/index.css
  frontend/src/pages/DetailPage.tsx
  frontend/tailwind.config.js
Labels: 디자인

#13 Be/#4 Open api에서 받아온 데이터 DB에 저장
  backend/docker-compose.yml
  backend/src/main/java/com/example/backend/api/data/dto/request/FestivalAPIRequest.java
  backend/src/main/java/com/example/backend/api/data/dto/response/FestivalAPIResponse.java
  backend/src/main/java/com/example/backend/api/data/vo/FeativalData.java
  backend/src/main/java/com/example/backend/api/data/vo/FestivalRow.java
  backend/src/main/java/com/example/backend/api/infra/SchedulerConfig.java
  backend/src/main/java/com/example/backend/api/service/SeoulOpenDataFestivalFetchAPI.java
  backend/src/main/java/com/example/backend/api/service/SeoulOpenDataService.java
  backend/src/main/java/com/example/backend/domain/festival/entity/Festival.java
  backend/src/main/java/com/example/backend/domain/festival/mapper/FestivalMapper.java
  backend/src/main/java/com/example/backend/domain/festival/repository/FestivalRepository.java
  backend/src/main/java/com/example/backend/domain/festival/service/FestivalService.java
  backend/src/main/resources/application-dev.yml
Labels: 기능구현

#14 Fe/#12 상세페이지 퍼블리싱
  frontend/src/App.tsx
  frontend/src/assets/images/jpg/SampleImage1.jpeg
  frontend/src/assets/images/png/MapSampleImage.png
  frontend/src/components/FestivalInformation.tsx
  frontend/src/components/MapInformation.tsx
  frontend/src/pages/DetailPage.tsx
Labels: 디자인

#19 Fe/#16 Tailwind CSS Prettier 세팅 완료
  frontend/.prettierrc
  frontend/package.json
  frontend/yarn.lock
Labels: 기타/세팅

#22 Fe/#21 프론트엔드 코드 Tailwind CSS Prettier 적용 완료
  frontend/src/components/FestivalInformation.tsx
  frontend/src/components/MapInformation.tsx
  frontend/src/components/NavBar.tsx
  frontend/src/pages/DetailPage.tsx
Labels: 기타/세팅
