Repository techeer-sv/SpotlightSeoul, pull requests merged in 2023-11, with the labels that each got.

#79 FE/#77 좋아요 조회수 기능 추가
  backend/src/main/java/com/example/backend/domain/festival/controller/FestivalController.java
  backend/src/main/java/com/example/backend/domain/festival/dto/response/FestivalDetailResponse.java
  backend/src/main/java/com/example/backend/domain/festival/dto/response/FestivalLikeResponse.java
  backend/src/main/java/com/example/backend/domain/festival/dto/response/FestivalResponse.java
  backend/src/main/java/com/example/backend/domain/festival/entity/Festival.java
  backend/src/main/java/com/example/backend/domain/festival/mapper/FestivalMapper.java
  backend/src/main/java/com/example/backend/domain/festival/repository/FestivalRepository.java
  backend/src/main/java/com/example/backend/domain/festival/service/FestivalService.java
Labels: 기능구현

#80 Fe/#76 네이버지도 및 검색바 수정
  frontend/src/components/MapInformation.tsx
  frontend/src/components/NavBar.tsx
Labels: 디자인, 오류수정

#84 Fe/#81 PostCard 무한스크롤 구현
  frontend/package.json
  frontend/src/components/NavBar.tsx
  frontend/src/components/PostCard.tsx
  frontend/src/pages/MainPage.tsx
  frontend/yarn.lock
Labels: 기능구현, 디자인, 리팩토링

#86 Be/#82 JWT 구현 및 검색 키워드 처리
  backend/build.gradle
  backend/src/main/java/com/example/backend/domain/festival/repository/FestivalRepositoryImpl.java
  backend/src/main/java/com/example/backend/domain/user/controller/UserController.java
  backend/src/main/java/com/example/backend/domain/user/dto/request/UserLoginRequest.java
  backend/src/main/java/com/example/backend/domain/user/dto/request/UserRefreshTokenRequest.java
  backend/src/main/java/com/example/backend/domain/user/entity/User.java
  backend/src/main/java/com/example/backend/domain/user/jwt/JwtAccessTokenResponse.java
  backend/src/main/java/com/example/backend/domain/user/jwt/JwtAuthorization.java
  backend/src/main/java/com/example/backend/domain/user/jwt/JwtAuthorizationArgumentResolver.java
  backend/src/main/java/com/example/backend/domain/user/jwt/JwtProvider.java
  backend/src/main/java/com/example/backend/domain/user/jwt/JwtResponse.java
  backend/src/main/java/com/example/backend/domain/user/jwt/UserTokenInfo.java
  backend/src/main/java/com/example/backend/domain/user/jwt/WebConfig.java
  backend/src/main/java/com/example/backend/domain/user/mapper/UserMapper.java
  backend/src/main/java/com/example/backend/domain/user/repository/UserRepository.java
  backend/src/main/java/com/example/backend/domain/user/service/UserService.java
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application-local.yml
Labels: 기능구현

#89 Fe/#87 로그인/회원가입 페이지 퍼블리싱
  frontend/package-lock.json
  frontend/src/App.tsx
  frontend/src/assets/images/png/Logo.png
  frontend/src/assets/images/png/signImg.png
  frontend/src/components/NavBar.tsx
  frontend/src/pages/LoginPage.tsx
  frontend/src/pages/SignupPage.tsx
  frontend/yarn.lock
Labels: 퍼블리싱

#91 Be/#51 데이터 업데이트 로직
  backend/src/main/java/com/example/backend/api/infra/PostconstructFestivalData.java
  backend/src/main/java/com/example/backend/api/infra/SchedulerConfig.java
  backend/src/main/java/com/example/backend/api/service/SeoulOpenDataFestivalFetchAPI.java
  backend/src/main/java/com/example/backend/api/service/SeoulOpenDataService.java
  backend/src/main/java/com/example/backend/domain/festival/entity/Festival.java
  backend/src/main/java/com/example/backend/domain/festival/mapper/FestivalMapper.java
  backend/src/main/java/com/example/backend/domain/festival/repository/FestivalRepository.java
  backend/src/main/java/com/example/backend/domain/festival/service/FestivalService.java
Labels: 기능구현

#97 Fe/#83 상세페이지 좋아요/조회수 구현
  frontend/src/assets/images/png/ViewIcon.png
  frontend/src/assets/images/svg/Favorite.svg
  frontend/src/assets/images/svg/Favorite_fill.svg
  frontend/src/components/FestivalInformation.tsx
  frontend/src/components/PostCard.tsx
  frontend/src/pages/DetailPage.tsx
Labels: 기능구현, 디자인

#98 Fe/#78 Footer 구현
  frontend/index.html
  frontend/src/App.tsx
  frontend/src/assets/images/svg/githubLogo.svg
  frontend/src/assets/images/svg/mediumLogo.svg
  frontend/src/components/Footer.tsx
  frontend/src/pages/LoginPage.tsx
  frontend/src/pages/SignupPage.tsx
Labels: 디자인
